include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - .flutter-plugins/**
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
    - avoid_dynamic_calls
    - prefer_single_quotes
